### ISSUE TITLE
Create: Test Rice Trait Name

### ISSUE THREAD

**Issue by ayabowork** [Planteome/CO_320-rice-traits#20]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Abenet    |
| **Program** | ILRI |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Test Rice Trait Name    |
| **Definition**         | This is a test rice trait name definition     |
| **Trait Class**        | Abiotic Stress   |
| **Measurement Method** | This is a test of the method of mesaurement        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | kg          |

**Comment by marieALaporte** [comment]
are you sure that this is a abiotic stress trait? I would rather put it under morphology
