### ISSUE TITLE
Create: test

### ISSUE THREAD

**Issue by KrishnaTO** [Planteome/CO_320-rice-traits#22]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Krishna Udaiwal    |
| **Program** | NA |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | test    |
| **Proposed Synonyms**  | test2     |
| **Definition**         | test test     |
| **Trait Class**        | Quality   |
| **Measurement Method** | visual        |
| **Measurement Type**   | Categorical |

#### Categories

| ID       | Description                   |
| -------- | ----------------------------- |
| **1** | test3    |
| **2** | test4    |

**Comment by elizabetharnaud** [comment]
You succeeded testing the form! thanks
