### ISSUE TITLE
obo file is invalid

### ISSUE THREAD

**Issue by cmungall** [Planteome/CO_320-rice-traits#3]
For context to this ticket, see checklist: https://github.com/Planteome/plant-trait-ontology/issues/374

This line is invalid:

https://github.com/Planteome/ibp-rice-traits/blob/master/rice-trait-ontology.obo#L54

last line in the stanza:

```
[Term]
id: CO_320:0000005
name: grain width
def: "Width of the dehulled grain with pericarp." [CO:rs]
comment: Enter the actual measurement of width in millimeters as the distance across the fertile lemma and the palea at the widest point.
synonym: "GrW" EXACT []
synonym: "seed width" RELATED []
xref: IRIS_TRAITID:1052
xref: TO:0000149
xref: TO:0000402
is_a: CO_320:0000001 ! morphological trait
Sample size = 10. At growth stage: 9.
```

**Comment by marieALaporte** [comment]
@cmungall the rice obo file is out of date. Could you use the TD instead?
I am about the delete the obo file from the repo
