### ISSUE TITLE
Variable request form is giving an error on "Update variable"

### ISSUE THREAD

**Issue by cooperl09** [Planteome/CO_320-rice-traits#9]
http://trait-requests.planteome.org/

After submission- "Internal Server Error"

**Comment by elserj** [comment]
Attaching log
[trait-submission.txt](https://github.com/Planteome/ibp-rice-traits/files/4013530/trait-submission.txt)

**Comment by elserj** [comment]
Closing. Fixed with proper download of "Full release" version of ontology
